version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  JVM-Test:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "geohash/build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: ./gradlew :geohash:dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "geohash/build.gradle" }}

      # run tests!
      - run: ./gradlew jvmTest

      - store_test_results:
          path: geohash/build/test-results

  Javascript-Browser-Test:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk-node-browsers

    environment:
      CHROME_BIN: "/usr/bin/google-chrome"

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "geohash/build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: ./gradlew :geohash:dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "geohash/build.gradle" }}

      # run tests!
      - run: ./gradlew jsBrowserTest

      - store_test_results:
          path: geohash/build/test-results

  Javascript-Node-Test:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk-node

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "geohash/build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: ./gradlew :geohash:dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "geohash/build.gradle" }}

      # run tests!
      - run: ./gradlew jsNodeTest

      - store_test_results:
          path: geohash/build/test-results

  Linux-Native-Test:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "geohash/build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - restore_cache:
          name:
          keys:
            - v1-native-dependencies-{{ checksum "geohash/build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-native-dependencies-

      - run:
          name: Download dependencies
          command: |
            ./gradlew :geohash:dependencies
            ./gradlew :geohash:compileKotlinLinux

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "geohash/build.gradle" }}

      - save_cache:
          paths:
            - ~/.konan/dependencies
          key: v1-native-dependencies-{{ checksum "geohash/build.gradle" }}

      # run tests!
      - run: ./gradlew linuxTest

      - store_test_results:
          path: geohash/build/test-results

  Windows-Native-Test:
    executor:
      name: win/default

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "geohash\\build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Download dependencies
          command: |
            .\gradlew.bat :geohash:dependencies

      - save_cache:
          paths:
            - ~\.gradle
          key: v1-dependencies-{{ checksum "geohash\\build.gradle" }}

      # run tests!
      - run: .\gradlew.bat windowsTest

      - store_test_results:
          path: geohash\build\test-results

workflows:
  version: 2
  Tests:
    jobs:
      - JVM-Test
      - Javascript-Browser-Test
      - Javascript-Node-Test
      - Linux-Native-Test
      - Windows-Native-Test

